"use client";
import Slider1 from "@/components/ImageCarousel";
import Footer from "@/components/footer";
import Navbar from "@/components/navigationBar";
import ReviewComponent from "@/components/reviewcomponent";
import Head from "next/head";
import Link from "next/link";
import { IoIosArrowForward } from "react-icons/io";
import { MdHome } from "react-icons/md";

export default function Home() {
  return (
    <div className="min-h-screen bg-gray-100">
      <Head>
        <title>Sri Lanka Lak Travel Destination</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white  ">
        <section className="">
          <nav className="z-20 w-screen lg:absolute">
            <Navbar />
          </nav>
          <div className="relative w-screen h-full">
            <div className="relative w-screen h-full">
              <div className="relative w-screen h-full">
                <img
                  src="https://i.imgur.com/jMFbSSb.jpg"
                  className="w-screen h-screen object-cover"
                  alt="Background"
                />
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                  <div className="text-white text-4xl font-bold drop-shadow-md mb-4">
                    About Us
                  </div>
                  <div className="flex items-center text-white text-2xl font-bold drop-shadow-md">
                    <Link href="/">
                      {" "}
                      <MdHome color="" size={30} className="mr-2" />{" "}
                    </Link>
                    <span>
                      {" "}
                      <Link href="/">Home</Link>
                    </span>

                    <IoIosArrowForward color="" size={30} className="mx-2" />
                    <span>About Us</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div
            className="relative flex items-center justify-center bg-cover bg-center"
            style={{
              backgroundImage: "url('https://i.imgur.com/0Onzutl.jpg')",
            }}
          >
            <div className="bg-white bg-opacity-75 p-5 rounded-lg  text-center">
              <div className="text-4xl lg:px-16 px-5 mb-5">
                <div className="font-semibold text-blue-600">
                  We focus on bringing the best
                </div>
                <div className="text-green-600 font-semibold">
                  Travel Experience
                </div>
              </div>
              <div className="text-3xl lg:px-16 px-5 font-semibold text-blue-800 mb-5">
                Who we are
              </div>
              <div className="text-slate-600 px-5 lg:px-16 font-medium">
                Sri Lanka Lak Travel Destinations has been organizing fantastic
                tours in Sri Lanka for tourists from all over the world over the
                past ten years. Our prices are reasonable and our tours provide
                high standards of both comfort and safety. We keep abreast of
                all the latest health and safety requirements, so as to ensure
                that our clients can have a thoroughly enjoyable and safe
                vacation. The Sri Lanka Lak Travel Destinations company has
                well-trained and experienced drivers with in-depth knowledge of
                the history and geography of Sri Lanka. Come and discover
                historical places of interest throughout the island. Learn about
                the diverse flora and fauna. Marvel at the traditional beauty,
                superb beaches, changing landscape and wonderful food of this
                splendid island – also known as ”the land of smiles”. Take home
                with you wonderful memories with Sri Lanka Lak Travel
                Destinations. We’ll be waiting!
              </div>
            </div>
          </div>
        </section>
        <ReviewComponent />
        <footer>
          <Footer />
        </footer>
      </main>
    </div>
  );
}
