import Footer from "@/components/footer";
import Navbar from "@/components/navigationBar";
import Head from "next/head";
import Link from "next/link";
import { IoIosArrowForward } from "react-icons/io";
import { MdHome } from "react-icons/md";
import { tourPackages } from "@/database/tourpackages";
import TourPackage from "./tourpackageCard";
export default function Home() {
  return (
    <div className="min-h-screen bg-gray-100">
      <Head>
        <title>Sri Lanka Lak Travel Destination</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white  ">
        <section className="">
          <nav className="z-20 w-screen lg:absolute">
            <Navbar />
          </nav>
          <div className="relative w-screen h-full">
            <div className="relative w-screen h-full">
              <div className="relative w-screen h-full">
                <img
                  src="https://i.imgur.com/OCysyuI.jpg"
                  className="w-screen lg:h-screen h-[50vh] object-cover"
                  alt="Background"
                />
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                  <div className="text-white text-4xl font-bold drop-shadow-md mb-4 mx-auto">
                    Tour Packages in Sri Lanka
                  </div>
                  <div className="flex items-center text-white text-2xl font-bold drop-shadow-md">
                    <Link href="/">
                      {" "}
                      <MdHome color="" size={30} className="mr-2" />{" "}
                    </Link>
                    <span>
                      {" "}
                      <Link href="/">Home</Link>
                    </span>

                    <IoIosArrowForward color="" size={30} className="mx-2" />
                    <span> Tour Packages</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="relative flex items-center justify-center bg-cover bg-center">
            <div className="bg-white bg-opacity-75 p-5 rounded-lg  text-center">
              <div className=" text-slate-800  px-5 lg:px-16 font-medium text-justify">
                {" "}
                Looking for the best tour packages in Sri Lanka? Look no
                further! At our Company, we offer a wide range of packages to
                choose from, perfect for all kinds of travelers. Whether you’re
                a couple looking for a romantic getaway, a family looking for
                some fun in the sun, or a group of friends wanting to explore
                everything this beautiful country has to offer, we have the
                perfect package for you. Our packages include everything you
                need for a hassle-free holiday, from accommodation and
                transportation to sightseeing and meals. And we offer packages
                for all kinds of budgets, so you can find the perfect one that
                fits your needs and your budget. So what are you waiting for?
                Book your Sri Lankan holiday today! Book your Tour Packages in
                Sri Lanka with Us!
              </div>
            </div>
          </div>
          <div className="text-4xl lg:px-16 px-5 mb-5 text-center font-sans"></div>
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 w-full lg:w-[80vw] mx-auto p-5">
            {tourPackages.map((packageInfo) => (
              <TourPackage id={packageInfo.id} key={packageInfo.id} />
            ))}
          </div>
          <div className=" h-10"></div>
        </section>
        <footer>
          <Footer />
        </footer>
      </main>
    </div>
  );
}
