export const dayexcursions = [
    {
      id:"1",
      name: "Jaffna Day Tour",
      imgUrl: "https://i.imgur.com/wOgu2Xj.jpg",
      description: "Jaffna market and city",
      numOfDays: "One",
      numOfPeople: "0-7",
      season: "",
    },
    { id:"2",
      name: "Kandy Day Tour",
      imgUrl: "https://i.imgur.com/FqojsAR.jpg",
      description: "Jaffna market and city",
      numOfDays: "One",
      numOfPeople: "0-7",
      season: "",
    },
    { id:"3",
      name: "Sigiriya Day Tour",
      imgUrl: "https://i.imgur.com/dpGXe2b.jpg",
      description: "Jaffna market and city",
      numOfDays: "One",
      numOfPeople: "0-7",
      season: "",
    },
    { id:"4",
      name: "Kithulgala Day Tour",
      imgUrl: "https://i.imgur.com/gFrQnv0.jpg",
      description: "Jaffna market and city",
      numOfDays: "One",
      numOfPeople: "0-7",
      season: "",
    },
    { id:"5",
      name: "Galle Day Tour",
      imgUrl: "https://i.imgur.com/wmOq8kl.jpg",
      description: "Jaffna market and city",
      numOfDays: "One",
      numOfPeople: "0-7",
      season: "",
    },
    { id:"6",
      name: "Trincomalee Tour",
      imgUrl: "https://i.imgur.com/xXUx8d1.jpg",
      description: "Jaffna market and city",
      numOfDays: "One",
      numOfPeople: "0-7",
      season: "",
    },
  ];
  
  