export const tourPackages = [
  {
    id: "1",
    name: "Jaffna Day Tour",
    imgUrl: "https://i.imgur.com/wOgu2Xj.jpg",
    description: "Jaffna market and city",
    numOfDays: "Four",
    numOfNights: "Three",
    numOfPeople: "0-7",
    season: "",
    longDescription:
      "Looking for things to do in Colombo? Our Colombo City Tour is the perfect way to see all the best sights the city has to offer! From bustling markets to ancient temples, Colombo is a city full of culture and history. Our knowledgeable and experienced guides will take you on a tour of all the best places to visit in Colombo, including Fort, Pettah and Slave Island. We also offer a range of optional extras, such as a visit to the National Museum or a trip to a tea plantation, so you can make the most of your time in this fascinating city. So what are you waiting for? Book your Colombo City Tour today!",
    destinations: ["Jaffna", "Vauniya", "Mulatiu", "Kilinochchi"],
    images: [
      "https://i.imgur.com/wmOq8kl.jpg",
      "https://i.imgur.com/GLxeiND.jpg",
      "https://i.imgur.com/OCysyuI.jpg",
      "https://i.imgur.com/7GwH6xu.jpg",
    ],
    difficulty: "Easy",
    tourtype: "Private , Adventure , sightseeing",
    date: "All year round",
    touritinerary: [
      {
        title: "DAY 01 - ARRIVED AT AIRPORT --> SIGIRIYA",
        desc: "Welcome to Sri Lanka , Pick up from the Colombo airport and drive to Sigiriya. Check-In to the hotel and leisurely spend the day at the Hotel in Sigiriya.",
        point: "Stay Overnight In Sigiriya.",
      },
      {
        title: "DAY 02 - ARRIVED AT AIRPORT --> SIGIRIYA",
        desc: "Welcome to Sri Lanka , Pick up from the Colombo airport and drive to Sigiriya. Check-In to the hotel and leisurely spend the day at the Hotel in Sigiriya.",
        point: "Stay Overnight In Sigiriya.",
      },
      {
        title: "DAY 03 - ARRIVED AT AIRPORT --> SIGIRIYA",
        desc: "Welcome to Sri Lanka , Pick up from the Colombo airport and drive to Sigiriya. Check-In to the hotel and leisurely spend the day at the Hotel in Sigiriya.",
        point: "Stay Overnight In Sigiriya.",
      },
    ],
  },

  {
    id: "2",
    name: "Kandy Day Tour",
    imgUrl: "https://i.imgur.com/FqojsAR.jpg",
    description: "Jaffna market and city",
    numOfDays: "One",
    numOfNights: "One",
    numOfPeople: "0-7",
    season: "",
    longDescription:
      "Looking for things to do in Colombo? Our Colombo City Tour is the perfect way to see all the best sights the city has to offer! From bustling markets to ancient temples, Colombo is a city full of culture and history. Our knowledgeable and experienced guides will take you on a tour of all the best places to visit in Colombo, including Fort, Pettah and Slave Island. We also offer a range of optional extras, such as a visit to the National Museum or a trip to a tea plantation, so you can make the most of your time in this fascinating city. So what are you waiting for? Book your Colombo City Tour today!",
    destinations: ["A", "B", "C"],
    images: [
      "https://i.imgur.com/wmOq8kl.jpg",
      "https://i.imgur.com/GLxeiND.jpg",
      "https://i.imgur.com/OCysyuI.jpg",
      "https://i.imgur.com/7GwH6xu.jpg",
    ],
    difficulty: "Easy",
    tourtype: "Private , Adventure , sightseeing",
    date: "All year round",
    touritinerary: [
      {
        title: "DAY 01 - ARRIVED AT AIRPORT --> SIGIRIYA",
        desc: "Welcome to Sri Lanka , Pick up from the Colombo airport and drive to Sigiriya. Check-In to the hotel and leisurely spend the day at the Hotel in Sigiriya.",
        point: "Stay Overnight In Sigiriya.",
      },
      {
        title: "DAY 02 - ARRIVED AT AIRPORT --> SIGIRIYA",
        desc: "Welcome to Sri Lanka , Pick up from the Colombo airport and drive to Sigiriya. Check-In to the hotel and leisurely spend the day at the Hotel in Sigiriya.",
        point: "Stay Overnight In Sigiriya.",
      },
      {
        title: "DAY 03 - ARRIVED AT AIRPORT --> SIGIRIYA",
        desc: "Welcome to Sri Lanka , Pick up from the Colombo airport and drive to Sigiriya. Check-In to the hotel and leisurely spend the day at the Hotel in Sigiriya.",
        point: "Stay Overnight In Sigiriya.",
      },
    ],
  },
  {
    id: "3",
    name: "Sigiriya Day Tour",
    imgUrl: "https://i.imgur.com/dpGXe2b.jpg",
    description: "Jaffna market and city",
    numOfDays: "One",
    numOfNights: "One",
    numOfPeople: "0-7",
    season: "",
    longDescription:
      "Looking for things to do in Colombo? Our Colombo City Tour is the perfect way to see all the best sights the city has to offer! From bustling markets to ancient temples, Colombo is a city full of culture and history. Our knowledgeable and experienced guides will take you on a tour of all the best places to visit in Colombo, including Fort, Pettah and Slave Island. We also offer a range of optional extras, such as a visit to the National Museum or a trip to a tea plantation, so you can make the most of your time in this fascinating city. So what are you waiting for? Book your Colombo City Tour today!",
    destinations: ["A", "B", "C"],
    images: [
      "https://i.imgur.com/wmOq8kl.jpg",
      "https://i.imgur.com/GLxeiND.jpg",
      "https://i.imgur.com/OCysyuI.jpg",
      "https://i.imgur.com/7GwH6xu.jpg",
    ],
    difficulty: "Easy",
    tourtype: "Private , Adventure , sightseeing",
    date: "All year round",
    touritinerary: [
      {
        title: "DAY 01 - ARRIVED AT AIRPORT --> JAFFNA",
        desc: "Welcome to Sri Lanka , Pick up from the Colombo airport and drive to Sigiriya. Check-In to the hotel and leisurely spend the day at the Hotel in Sigiriya.",
        point: "Stay Overnight In Sigiriya.",
      },
      {
        title: "DAY 02 - ARRIVED AT AIRPORT --> SIGIRIYA",
        desc: "Welcome to Sri Lanka , Pick up from the Colombo airport and drive to Sigiriya. Check-In to the hotel and leisurely spend the day at the Hotel in Sigiriya.",
        point: "Stay Overnight In Sigiriya.",
      },
      {
        title: "DAY 03 - ARRIVED AT AIRPORT --> SIGIRIYA",
        desc: "Welcome to Sri Lanka , Pick up from the Colombo airport and drive to Sigiriya. Check-In to the hotel and leisurely spend the day at the Hotel in Sigiriya.",
        point: "Stay Overnight In Sigiriya.",
      },
    ],
  },
  {
    id: "4",
    name: "Kithulgala Day Tour",
    imgUrl: "https://i.imgur.com/gFrQnv0.jpg",
    description: "Jaffna market and city",
    numOfDays: "One",
    numOfNights: "One",
    numOfPeople: "0-7",
    season: "",
    longDescription:
      "Looking for things to do in Colombo? Our Colombo City Tour is the perfect way to see all the best sights the city has to offer! From bustling markets to ancient temples, Colombo is a city full of culture and history. Our knowledgeable and experienced guides will take you on a tour of all the best places to visit in Colombo, including Fort, Pettah and Slave Island. We also offer a range of optional extras, such as a visit to the National Museum or a trip to a tea plantation, so you can make the most of your time in this fascinating city. So what are you waiting for? Book your Colombo City Tour today!",
    destinations: ["A", "B", "C"],
    images: [
      "https://i.imgur.com/wmOq8kl.jpg",
      "https://i.imgur.com/GLxeiND.jpg",
      "https://i.imgur.com/OCysyuI.jpg",
      "https://i.imgur.com/7GwH6xu.jpg",
    ],
    difficulty: "Easy",
    tourtype: "Private , Adventure , sightseeing",
    date: "All year round",
    touritinerary: [
      {
        title: "DAY 01 - ARRIVED AT AIRPORT --> SIGIRIYA",
        desc: "Welcome to Sri Lanka , Pick up from the Colombo airport and drive to Sigiriya. Check-In to the hotel and leisurely spend the day at the Hotel in Sigiriya.",
        point: "Stay Overnight In Sigiriya.",
      },
      {
        title: "DAY 02 - ARRIVED AT AIRPORT --> SIGIRIYA",
        desc: "Welcome to Sri Lanka , Pick up from the Colombo airport and drive to Sigiriya. Check-In to the hotel and leisurely spend the day at the Hotel in Sigiriya.",
        point: "Stay Overnight In Sigiriya.",
      },
      {
        title: "DAY 03 - ARRIVED AT AIRPORT --> SIGIRIYA",
        desc: "Welcome to Sri Lanka , Pick up from the Colombo airport and drive to Sigiriya. Check-In to the hotel and leisurely spend the day at the Hotel in Sigiriya.",
        point: "Stay Overnight In Sigiriya.",
      },
    ],
  },
  {
    id: "5",
    name: "Galle Day Tour",
    imgUrl: "https://i.imgur.com/wmOq8kl.jpg",
    description: "Jaffna market and city",
    numOfDays: "One",
    numOfNights: "One",
    numOfPeople: "0-7",
    season: "",
    longDescription:
      "Looking for things to do in Colombo? Our Colombo City Tour is the perfect way to see all the best sights the city has to offer! From bustling markets to ancient temples, Colombo is a city full of culture and history. Our knowledgeable and experienced guides will take you on a tour of all the best places to visit in Colombo, including Fort, Pettah and Slave Island. We also offer a range of optional extras, such as a visit to the National Museum or a trip to a tea plantation, so you can make the most of your time in this fascinating city. So what are you waiting for? Book your Colombo City Tour today!",
    destinations: ["A", "B", "C"],
    images: [
      "https://i.imgur.com/wmOq8kl.jpg",
      "https://i.imgur.com/GLxeiND.jpg",
      "https://i.imgur.com/OCysyuI.jpg",
      "https://i.imgur.com/7GwH6xu.jpg",
    ],
    difficulty: "Easy",
    tourtype: "Private , Adventure , sightseeing",
    date: "All year round",
    touritinerary: [
      {
        title: "DAY 01 - ARRIVED AT AIRPORT --> SIGIRIYA",
        desc: "Welcome to Sri Lanka , Pick up from the Colombo airport and drive to Sigiriya. Check-In to the hotel and leisurely spend the day at the Hotel in Sigiriya.",
        point: "Stay Overnight In Sigiriya.",
      },
      {
        title: "DAY 02 - ARRIVED AT AIRPORT --> SIGIRIYA",
        desc: "Welcome to Sri Lanka , Pick up from the Colombo airport and drive to Sigiriya. Check-In to the hotel and leisurely spend the day at the Hotel in Sigiriya.",
        point: "Stay Overnight In Sigiriya.",
      },
      {
        title: "DAY 03 - ARRIVED AT AIRPORT --> SIGIRIYA",
        desc: "Welcome to Sri Lanka , Pick up from the Colombo airport and drive to Sigiriya. Check-In to the hotel and leisurely spend the day at the Hotel in Sigiriya.",
        point: "Stay Overnight In Sigiriya.",
      },
    ],
  },
  {
    id: "6",
    name: "Anuradhapura Tour",
    imgUrl: "https://i.imgur.com/xXUx8d1.jpg",
    description: "Jaffna market and city",
    numOfDays: "One",
    numOfNights: "One",
    numOfPeople: "0-7",
    season: "",
    longDescription:
      "Looking for things to do in Colombo? Our Colombo City Tour is the perfect way to see all the best sights the city has to offer! From bustling markets to ancient temples, Colombo is a city full of culture and history. Our knowledgeable and experienced guides will take you on a tour of all the best places to visit in Colombo, including Fort, Pettah and Slave Island. We also offer a range of optional extras, such as a visit to the National Museum or a trip to a tea plantation, so you can make the most of your time in this fascinating city. So what are you waiting for? Book your Colombo City Tour today!",
    destinations: ["A", "B", "C"],
    images: [
      "https://i.imgur.com/wmOq8kl.jpg",
      "https://i.imgur.com/GLxeiND.jpg",
      "https://i.imgur.com/OCysyuI.jpg",
      "https://i.imgur.com/7GwH6xu.jpg",
    ],
    difficulty: "Easy",
    tourtype: "Private , Adventure , sightseeing",
    date: "All year round",
    touritinerary: [
      {
        title: "DAY 01 - ARRIVED AT AIRPORT --> SIGIRIYA",
        desc: "Welcome to Sri Lanka , Pick up from the Colombo airport and drive to Sigiriya. Check-In to the hotel and leisurely spend the day at the Hotel in Sigiriya.",
        point: "Stay Overnight In Sigiriya.",
      },
      {
        title: "DAY 02 - ARRIVED AT AIRPORT --> SIGIRIYA",
        desc: "Welcome to Sri Lanka , Pick up from the Colombo airport and drive to Sigiriya. Check-In to the hotel and leisurely spend the day at the Hotel in Sigiriya.",
        point: "Stay Overnight In Sigiriya.",
      },
      {
        title: "DAY 03 - ARRIVED AT AIRPORT --> SIGIRIYA",
        desc: "Welcome to Sri Lanka , Pick up from the Colombo airport and drive to Sigiriya. Check-In to the hotel and leisurely spend the day at the Hotel in Sigiriya.",
        point: "Stay Overnight In Sigiriya.",
      },
    ],
  },
];
