import Footer from "@/components/footer";
import Navbar from "@/components/navigationBar";
import ContactSection from "@/components/quickcontact";
import ReviewComponent from "@/components/reviewcomponent";
import Head from "next/head";
import Link from "next/link";
import { IoIosArrowForward } from "react-icons/io";
import { MdHome } from "react-icons/md";
//import DestinationCard from "./destinationcard";
import { destinations } from "@/database/destinations"; 

export default function Home() {
  return (
    <div className="min-h-screen bg-gray-100">
      <Head>
        <title>Sri Lanka Lak Travel Destination</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white  ">
        <section className="">
          <nav className="z-20 w-screen lg:absolute">
            <Navbar />
          </nav>
          <div className="relative w-screen h-full">
            <div className="relative w-screen h-full">
              <div className="relative w-screen h-full">
                <img
                  src="https://i.imgur.com/OM7VTcn.jpg"
                  className="w-screen lg:h-screen h-[50vh] object-cover"
                  alt="Background"
                />
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                  <div className="text-white text-4xl font-bold drop-shadow-md mb-4">
                    Destinations
                  </div>
                  <div className="flex items-center text-white text-2xl font-bold drop-shadow-md">
                    <Link href="/">
                      {" "}
                      <MdHome color="" size={30} className="mr-2" />{" "}
                    </Link>
                    <span>
                      {" "}
                      <Link href="/">Home</Link>
                    </span>

                    <IoIosArrowForward color="" size={30} className="mx-2" />
                    <span>Destinations</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="relative flex items-center justify-center bg-cover bg-center">
            <div className="bg-white bg-opacity-75 p-5 rounded-lg  text-center">
              <div className="text-4xl lg:px-16 px-5 mb-5">
                <div className="font-semibold text-blue-600">
                  Tourists Destinations in Sri Lanka
                </div>
              </div>
              <div className="text-slate-600 px-5 lg:px-16 font-medium">
                Sri Lanka is a popular tourist destination for a reason: it’s
                gorgeous. This tiny island nation has a huge range of diverse
                landscapes to offer, from mountains and cliffs to waterfalls and
                beaches. And if that’s not enough, there are also temples. If
                you’re looking for beautiful places to visit in Sri Lanka, look
                no further. We’ve got a list of the top tourist attractions in
                Sri Lanka (Sri Lanka tourist places), along with tips on the
                best way to experience them. So, whether you’re looking for
                culture, adventure, or just some serious relaxation, Sri Lanka
                has something for you. SO, here are the best Sri Lanka Tourist
                Places.
              </div>
            </div>
          </div>
    
          <div>
          {/* <div className="pt-2 columns-2 md:columns-3 lg:columns-3 mx-2">
            {destinations.map((destination, index) => (
              <div key={index} className="relative mb-4 break-inside-avoid">
                <DestinationCard title={destination.title} imgUrl={destination.imgUrl} />
              </div>
            ))}
          </div> */}
          </div>
          <div>
            <ContactSection />
          </div>
        </section>
        <ReviewComponent />
        <footer>
          <Footer />
        </footer>
      </main>
    </div>
  );
}
