import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import WhatsAppIcon from "@/components/whatsAppIcon";
import { BooleanProvider } from "@/context/boolcontext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sri Lanka Lak Dream Travel Destination",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <BooleanProvider>{children}</BooleanProvider>
        <WhatsAppIcon />
        {/* <Enquirenow/> */}
      </body>
    </html>
  );
}
