
import Slider1 from "@/components/ImageCarousel";
import ReviewCarousel from "@/components/ReviewCarousel";
import Destination from "@/components/destination";
import Footer from "@/components/footer";
import Navbar from "@/components/navigationBar";
import Review from "@/components/review";
import ReviewComponent from "@/components/reviewcomponent";
import TourPackage from "@/components/tourPackage";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white  ">
        <section className="">
          <nav className="z-20 w-screen lg:absolute">
            <Navbar />
          </nav>
          <Slider1 />
        </section>
        <section>
          <div className=" flex-1 mt-2 lg:flex">
            <div className=" basis-1/2">
              <div className=" text-3xl lg:px-16 px-5 font-semibold text-slate-800">
                {" "}
                Explore amazing Sri Lanka with Lak Dream Travel Destination
              </div>
              <div className=" text-slate-600 px-5 lg:px-16  font-medium p-3">
                Imagine exploring the beautiful country of Sri Lanka, touring
                ancient temples and Buddhist ruins, and enjoying the stunning
                beaches—all without having to worry about a thing. That’s what
                Chamila Tours – Private Driver in Sri Lanka offers: an
                all-inclusive, hassle-free experience that will let you see the
                best of Sri Lanka. We understand that every traveler is
                different, so we offer a variety of tour packages that can be
                customized to meet your specific needs. Whether you’re looking
                for a leisurely vacation or an adventure-filled getaway, our
                team of experts will help you make the most of your time in Sri
                Lanka. We hope you’ll consider Chamila Tours – Private Driver in
                Sri Lanka when planning your next trip to Sri Lanka.
              </div>
              <div className="text-blue-600 px-5 lg:px-16  font-medium p-3 flex-1 lg:flex text-center">
                <div>
                  <img src="https://i.imgur.com/c2DVMJA.png" />
                  <div className=" pt-6">Experienced Private Driver</div>
                </div>
                <div>
                  <img src="https://i.imgur.com/zvr4Pw7.png" />
                  <div>Different Destinations</div>
                </div>
                <div>
                  <img src="https://i.imgur.com/oOBh1qs.png" />
                  <div>Quick Response</div>
                </div>
              </div>
            </div>
            <div className=" basis-1/2">
              <img src="https://i.imgur.com/FLN1VBo.jpg" />
            </div>
          </div>
        </section>
        <section className=" bg-slate-400">
          <div className=" text-3xl lg:px-16 px-5 font-semibold text-white text-center p-3 bg-red-800 rounded-lg m-4">
            Our most popular Tour Packages
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 w-full lg:w-[80vw] mx-auto p-5">
            <TourPackage
              title={"Heritage Tour"}
              imgUrl={"https://i.imgur.com/RNu0xm9.jpg"}
              description={
                "This tour package is included the main historical, architectural, and sacred places which included into the Cultural Triangle in Sri Lanka that you must travel to."
              }
              numOfDays={"7"}
              numOfNights={"6"}
              season={"All Year Round"}
            />
            <TourPackage
              title={"Heritage Tour"}
              imgUrl={"https://i.imgur.com/wOgu2Xj.jpg"}
              description={
                "This tour package is included the main historical, architectural, and sacred places which included into the Cultural Triangle in Sri Lanka that you must travel to."
              }
              numOfDays={"7"}
              numOfNights={"6"}
              season={"All Year Round"}
            />
            <TourPackage
              title={"Heritage Tour"}
              imgUrl={"https://i.imgur.com/UYrJ2L0.jpg"}
              description={
                "This tour package is included the main historical, architectural, and sacred places which included into the Cultural Triangle in Sri Lanka that you must travel to."
              }
              numOfDays={"7"}
              numOfNights={"6"}
              season={"All Year Round"}
            />
          </div>
          <div className=" text-3xl lg:px-16 px-5 font-semibold text-white text-center p-3 bg-red-800 rounded-lg m-4">
            Popular destinations
          </div>
          <div className="flex-1 lg:flex">
            <Destination
              title="Slit fisherman"
              imgUrl="https://i.imgur.com/Ypjeksa.jpg"
            />
            <Destination
              title="Jaffna"
              imgUrl="https://i.imgur.com/ERfq4i2.jpg"
            />

            <Destination
              title="Nuwara Eliya"
              imgUrl="https://i.imgur.com/UYrJ2L0.jpg"
            />

            <Destination
              title="Kandy"
              imgUrl="https://i.imgur.com/oke6pTe.jpg"
            />
          </div>
          <ReviewComponent/>
        </section>
        <footer>
          <Footer/>
        </footer>
      </main>
    </div>
  );
}
