import Footer from "@/components/footer";
import Navbar from "@/components/navigationBar";
import Head from "next/head";
import Link from "next/link";
import { IoIosArrowForward, IoMdDoneAll } from "react-icons/io";
import { MdHome } from "react-icons/md";
import { dayexcursions } from "@/database/dayexcursions";
import TourPackage from "../Tour-Packages/tourpackageCard";
export default function Home() {
  return (
    <div className="min-h-screen bg-gray-100">
      <Head>
        <title>Sri Lanka Lak Travel Destination</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white  ">
        <section className="">
          <nav className="z-20 w-screen lg:absolute">
            <Navbar />
          </nav>
          <div className="relative w-screen h-full">
            <div className="relative w-screen h-full">
              <div className="relative w-screen h-full">
                <img
                  src="https://i.imgur.com/OM7VTcn.jpg"
                  className="w-screen lg:h-screen h-[50vh] object-cover"
                  alt="Background"
                />
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                  <div className="text-white text-4xl font-bold drop-shadow-md mb-4">
                    Day Tours in Sri Lanka
                  </div>
                  <div className="flex items-center text-white text-2xl font-bold drop-shadow-md">
                    <Link href="/">
                      {" "}
                      <MdHome color="" size={30} className="mr-2" />{" "}
                    </Link>
                    <span>
                      {" "}
                      <Link href="/">Home</Link>
                    </span>

                    <IoIosArrowForward color="" size={30} className="mx-2" />
                    <span>Day Excursions</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="relative flex items-center justify-center bg-cover bg-center">
            <div className="bg-white bg-opacity-75 p-5 rounded-lg  text-center">
              <div className=" text-slate-800  px-5 lg:px-16 font-medium text-justify">
                {" "}
                Our one-day tour packages are the perfect way to see all the
                best highlights of Sri Lanka in a short period of time. We offer
                a wide variety of one day tour packages that will take you to
                the best places in Sri Lanka. From the ancient city of
                Anuradhapura to the beautiful beaches of Trincomalee, our day
                tours cover all the best attractions in Sri Lanka. Our
                knowledgeable and friendly tour guides will take care of you
                every step of the way, and our comfortable and air-conditioned
                vehicles will make sure that you enjoy your day trip to the
                fullest. So if you’re looking for a fun and affordable way to
                see all the best that Sri Lanka has to offer, look no further
                than Sri Lanka Lak Dream Travel Destination!
              </div>
            </div>
          </div>
          <div className="text-4xl lg:px-16 px-5 mb-5 text-center font-sans"></div>
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 w-full lg:w-[80vw] mx-auto p-5">
          {dayexcursions.map((packageInfo, index) => (
              <TourPackage id={packageInfo.id}              />
            ))}
           
          </div>
          <div className=" h-10">

          </div>
        </section>
        <footer>
          <Footer />
        </footer>
      </main>
    </div>
  );
}
