import Footer from "@/components/footer";
import Navbar from "@/components/navigationBar";
import ContactSection from "@/components/quickcontact";
import ReviewComponent from "@/components/reviewcomponent";
import VehicleComponent from "@/app/Hire-A-Car/vehiclecomponent";
import Head from "next/head";
import Link from "next/link";
import { IoIosArrowForward } from "react-icons/io";
import { MdHome } from "react-icons/md";

export default function Home() {
  return (
    <div className="min-h-screen bg-gray-100">
      <Head>
        <title>Sri Lanka Lak Travel Destination</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white  ">
        <section className="">
          <nav className="z-20 w-screen lg:absolute">
            <Navbar />
          </nav>
          <div className="relative w-screen h-full">
            <div className="relative w-screen h-full">
              <div className="relative w-screen h-full">
                <img
                  src="https://i.imgur.com/QdhxF3S.jpg"
                  className="w-screen h-screen object-cover"
                  alt="Background"
                />
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                  <div className="text-white text-4xl font-bold drop-shadow-md mb-4">
                    Hire a car
                  </div>
                  <div className="flex items-center text-white text-2xl font-bold drop-shadow-md">
                    <Link href="/">
                      {" "}
                      <MdHome color="" size={30} className="mr-2" />{" "}
                    </Link>
                    <span>
                      {" "}
                      <Link href="/">Home</Link>
                    </span>

                    <IoIosArrowForward color="" size={30} className="mx-2" />
                    <span>Hire a car</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="relative flex items-center justify-center bg-cover bg-center">
            <div className="bg-white bg-opacity-75 p-5 rounded-lg  text-center">
              <div className="text-4xl lg:px-16 px-5 mb-5">
                <div className="font-semibold text-blue-600">
                  Hire a Car in Sri Lanka
                </div>
              </div>
              <div className="text-slate-600 px-5 lg:px-16 font-medium">
                Sri Lanka is a beautiful country with plenty to see and do. Why
                not make the most of your time here by hiring a car with a
                driver? Chamila Tours, At our car hire company, we offer a wide
                range of vehicles to choose from, as well as a team of
                experienced drivers who know the best places to go in Sri Lanka.
                Whether you’re looking for a taxi to take you from the airport
                to your hotel or you want to explore more of the country with a
                private driver, we can help. We also offer car hire with a
                driver in Colombo, so you can explore the city at your own pace.
                Why not visit some of the city’s famous landmarks, such as the
                Colombo Fort, Gangaramaya Temple or the National Museum? Or
                maybe you’d rather explore the stunning beaches of Sri Lanka?
                Whatever you choose to do, we’re sure you’ll have a great time.
                Contact us today to hire a car with a driver in Sri Lanka!. We
                have Cars, Mini Van, Van – HI roof, Mini Bus & Bus Single Deck.
              </div>
            </div>
          </div>
          <div className="relative flex items-center justify-center bg-cover bg-center">
            <div className="bg-white bg-opacity-75 p-5 rounded-lg  text-center">
              <div className="text-4xl lg:px-16 px-5 mb-5">
                <div className="font-semibold text-slate-600">
                  TYPE OF VEHICLES TO CHOOSE
                </div>
              </div>
            </div>
          </div>
          <div>
            <VehicleComponent
              title={"Car"}
              imgUrl={"https://i.imgur.com/QdhxF3S.jpg"}
              facts={[
                "Toyota Corolla or Nissan Sedan",
                "Maximum 3 Passengers & enough Room for Baggage’s",
                "Fully Air Conditioned, Fully Insured, Perfect seat belts",
                "Onboard WiFi ",
              ]}
            />
          </div>
          <div>
            <ContactSection />
          </div>
        </section>
        <ReviewComponent />
        <footer>
          <Footer />
        </footer>
      </main>
    </div>
  );
}

