import Footer from "@/components/footer";
import Navbar from "@/components/navigationBar";
import ContactSection from "@/components/quickcontact";
import ReviewComponent from "@/components/reviewcomponent";
import VehicleComponent from "@/app/Hire-A-Car/vehiclecomponent";
import Head from "next/head";
import Link from "next/link";
import { IoIosArrowForward } from "react-icons/io";
import { MdHome } from "react-icons/md";
import { vehicles } from "@/database/vehicles";

export default function Home() {
  return (
    <div className="min-h-screen bg-gray-100">
      <Head>
        <title>Monkey Bird Travels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white  ">
        <section className="">
          <nav className="z-20 w-screen lg:absolute">
            <Navbar />
          </nav>
          <div className="relative w-screen h-full">
            <div className="relative w-screen h-full">
              <div className="relative w-screen h-full">
                <img
                  src="https://i.imgur.com/QdhxF3S.jpg"
                  className="w-screen lg:h-screen h-[50vh] object-cover"
                  alt="Background"
                />
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                  <div className="text-white text-4xl font-bold drop-shadow-md mb-4">
                    Hire a car
                  </div>
                  <div className="flex items-center text-white text-2xl font-bold drop-shadow-md">
                    <Link href="/">
                      {" "}
                      <MdHome color="" size={30} className="mr-2" />{" "}
                    </Link>
                    <span>
                      {" "}
                      <Link href="/">Home</Link>
                    </span>

                    <IoIosArrowForward color="" size={30} className="mx-2" />
                    <span>Hire a car</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="relative flex items-center justify-center bg-cover bg-center">
            <div className="bg-white bg-opacity-75 p-5 rounded-lg  text-center">
              <div className="text-4xl lg:px-16 px-5 mb-5">
                <div className="font-semibold text-blue-600">
                  Hire a Car in Sri Lanka
                </div>
              </div>
              <div className="text-slate-600 px-5 lg:px-16 font-medium">
                Sri Lanka is a land of breathtaking beauty, rich culture, and
                countless adventures waiting to be explored. Why not make your
                journey truly hassle-free by hiring a car with a professional
                driver? At Monkeybird Travels, we offer an extensive range of
                vehicles to suit your needs—from cars and mini-vans to high-roof
                vans, mini-buses, and single-deck buses—all driven by
                experienced and friendly drivers who know Sri Lanka inside out.
                Whether you need a reliable taxi to take you from the airport to
                your hotel, or you’re planning to explore the country’s hidden
                gems with a private driver, we’ve got you covered. For those
                staying in Colombo, our car hire services with drivers let you
                explore the city’s iconic landmarks, such as Colombo Fort,
                Gangaramaya Temple, and the National Museum, at your own pace.
                Prefer a relaxing day by the ocean? We can take you to Sri
                Lanka’s stunning beaches, where golden sands and turquoise
                waters await. Whatever your itinerary, our team is here to
                ensure a safe, comfortable, and unforgettable experience.
                Contact us today to book your vehicle and driver with Monkeybird
                Travels, and get ready to embark on a journey filled with
                memories to treasure forever!
              </div>
            </div>
          </div>
          <div className="relative flex items-center justify-center bg-cover bg-center">
            <div className="bg-white bg-opacity-75 p-5 rounded-lg  text-center">
              <div className="text-4xl lg:px-16 px-5 mb-5">
                <div className="font-semibold text-slate-600">
                  TYPE OF VEHICLES TO CHOOSE
                </div>
              </div>
            </div>
          </div>
          <div>
            {vehicles.map((vehicle, index) => (
              <VehicleComponent
                key={index}
                title={vehicle.title}
                imgUrl={vehicle.imgUrl}
                facts={vehicle.facts}
              />
            ))}
          </div>
          <div>
            <ContactSection />
          </div>
        </section>
        <ReviewComponent />
        <footer>
          <Footer />
        </footer>
      </main>
    </div>
  );
}
