"use client";
import Footer from "@/components/footer";
import Navbar from "@/components/navigationBar";
import ReviewComponent from "@/components/reviewcomponent";
import { TypeAnimation } from "react-type-animation";
import Head from "next/head";
import Link from "next/link";
import { IoIosArrowForward } from "react-icons/io";
import { MdHome } from "react-icons/md";
import { ContactDetails, QuickContact } from "@/components/quickcontact";
import AutoChangingTourPackages from "./autochangingpackages";
import TailorMadeTours from "./tailormadetourdform";

export default function Home() {
  return (
    <div className="min-h-screen bg-gray-100">
      <Head>
        <title>Monkey Bird Travels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white  ">
        <section className="">
          <nav className="z-20 w-screen lg:absolute">
            <Navbar />
          </nav>
          <div className="relative w-screen h-full">
            <div className="relative w-screen h-full">
              <div className="relative w-screen h-full">
                <img
                  src="https://i.imgur.com/kri7cZJ.jpg"
                  className="w-screen lg:h-screen h-[50vh] object-cover"
                  alt="Background"
                />
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                  <div className="text-white text-4xl font-bold drop-shadow-md mb-4">
                    Tailor Made Tours
                  </div>
                  <div className="flex items-center text-white text-2xl font-bold drop-shadow-md">
                    <Link href="/">
                      {" "}
                      <MdHome color="" size={30} className="mr-2" />{" "}
                    </Link>
                    <span>
                      {" "}
                      <Link href="/">Home</Link>
                    </span>

                    <IoIosArrowForward color="" size={30} className="mx-2" />
                    <span>Tailor Made Tours</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="relative flex items-center justify-center bg-cover bg-center">
            <div className="bg-white bg-opacity-75 p-5 rounded-lg  text-center">
              <div className="text-4xl lg:px-16 px-5 mb-5">
                <div className="font-semibold text-blue-600">
                Craft Your Dream Holiday in Sri Lanka with Us!
                </div>
              </div>
              <div className="text-slate-600 px-5 lg:px-16 font-medium">
                Looking for the perfect tailor-made holiday in Sri Lanka? Your
                search ends here! Our team of travel experts specializes in
                creating personalized Sri Lankan holiday experiences designed to
                match your interests and preferences. Whether you are seeking a
                relaxing beach getaway or an adrenaline-filled adventure tour,
                we have something for everyone. From the breathtaking beaches of
                the south to the lush hill country and cultural wonders of Sri
                Lanka, we will help you discover the best destinations and
                experiences this enchanting island has to offer. Choose from our
                carefully curated holiday packages or let us design a custom
                itinerary just for you. We also provide a wide range of
                accommodation options, ensuring you will find the perfect place to
                stay—whether it is a luxury resort, boutique villa, or cozy
                guesthouse. With our convenient transport solutions, exploring
                Sri Lanka has never been easier. Make your dream holiday a
                reality with our tailor-made Sri Lankan tours. Let us take care
                of every detail, so you can focus on enjoying an unforgettable
                journey through one of the world s most beautiful destinations.
              </div>
            </div>
          </div>
          <div className="relative flex items-center justify-center bg-cover bg-center">
            <div className="bg-white bg-opacity-75 p-5 rounded-lg  text-center">
              <div className="text-4xl lg:px-16 px-5 mb-5">
                <div className="font-semibold text-slate-600">
                  <TypeAnimation
                    sequence={[
                      " Plan",
                      1000,
                      "Customize",
                      1000,
                      "Tailor Make ",
                      1000,
                    ]}
                    cursor={false}
                    speed={50}
                    repeat={0}
                    style={{ fontSize: "1em" }}
                    className=" text-yellow-500"
                  />{" "}
                  Your Journey
                </div>
              </div>
            </div>
          </div>
          <div className="flex-1 lg:flex">
      <TailorMadeTours />
      <div className="flex-1 mx-auto">
        <ContactDetails />
        <QuickContact />
      </div>
    </div>
        </section>
        <ReviewComponent />
        <footer>
          <Footer />
        </footer>
      </main>
    </div>
  );
}
