"use client"
import Footer from "@/components/footer";
import Navbar from "@/components/navigationBar";
import ReviewComponent from "@/components/reviewcomponent";
import { TypeAnimation } from "react-type-animation";
import Head from "next/head";
import Link from "next/link";
import { IoIosArrowForward } from "react-icons/io";
import { MdHome } from "react-icons/md";
import TailorMadeTours from "./tailormadetourdform";
import { ContactDetails, QuickContact } from "@/components/quickcontact";
import AutoChangingTourPackages from "./autochangingpackages";

export default function Home() {
  return (
    <div className="min-h-screen bg-gray-100">
      <Head>
        <title>Sri Lanka Lak Travel Destination</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white  ">
        <section className="">
          <nav className="z-20 w-screen lg:absolute">
            <Navbar />
          </nav>
          <div className="relative w-screen h-full">
            <div className="relative w-screen h-full">
              <div className="relative w-screen h-full">
                <img
                  src="https://i.imgur.com/kri7cZJ.jpg"
                  className="w-screen lg:h-screen h-[50vh] object-cover"
                  alt="Background"
                />
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                  <div className="text-white text-4xl font-bold drop-shadow-md mb-4">
                    Tailor Made Tours
                  </div>
                  <div className="flex items-center text-white text-2xl font-bold drop-shadow-md">
                    <Link href="/">
                      {" "}
                      <MdHome color="" size={30} className="mr-2" />{" "}
                    </Link>
                    <span>
                      {" "}
                      <Link href="/">Home</Link>
                    </span>

                    <IoIosArrowForward color="" size={30} className="mx-2" />
                    <span>Tailor Made Tours</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="relative flex items-center justify-center bg-cover bg-center">
            <div className="bg-white bg-opacity-75 p-5 rounded-lg  text-center">
              <div className="text-4xl lg:px-16 px-5 mb-5">
                <div className="font-semibold text-blue-600">
                  Tailor Made Tours Sri Lanka
                </div>
              </div>
              <div className="text-slate-600 px-5 lg:px-16 font-medium">
                Looking for the perfect tailor made holiday to Sri Lanka? Look
                no further! Our team of experts will work with you to create the
                perfect Sri Lankan holiday experience, tailored specifically to
                your needs and interests. From relaxing beach holidays to
                exciting adventure tours, we have something for everyone. Our
                experienced team will help you find the best destinations and
                experiences in Sri Lanka, so you can make the most of your time
                in this incredible country. We offer a range of tailor made
                holiday to sri lanka, or we can create a custom package just for
                you. We also have a wide range of accommodation options to
                choose from, so you can find the perfect place to stay during
                your holiday. And our range of transport options makes getting
                around Sri Lanka easy and convenient. With our tailor made
                holiday to sri lanka, you’ll have everything you need to make
                the most of your holiday in Sri Lanka.
              </div>
            </div>
          </div>
          <div className="relative flex items-center justify-center bg-cover bg-center">
            <div className="bg-white bg-opacity-75 p-5 rounded-lg  text-center">
              <div className="text-4xl lg:px-16 px-5 mb-5">
                <div className="font-semibold text-slate-600">
                <TypeAnimation
                    sequence={[
                      " Plan",
                      1000,
                      "Customize",
                      1000,
                      "Tailor Make ",
                      1000,
                    ]}
                    cursor={false}
                    speed={50}
                    repeat={0}
                    style={{ fontSize: "1em" }}
                   
                    className=" text-yellow-500"
                  /> Your Journey
                
                </div>
              </div>
            </div>
          </div>
          <div className=" flex-1 lg:flex">
            <TailorMadeTours/>
            <div className=" flex-1 mx-auto">
            <ContactDetails />
            <AutoChangingTourPackages/>
            <QuickContact />
            </div>
          </div>
        </section>
        <ReviewComponent />
        <footer>
          <Footer />
        </footer>
      </main>
    </div>
  );
}
