import Footer from "@/components/footer";
import Navbar from "@/components/navigationBar";
import Head from "next/head";
import Link from "next/link";
import { IoIosArrowForward } from "react-icons/io";
import { MdHome } from "react-icons/md";
import { tourPackages } from "@/database/tourpackages";
export default function Home() {
  return (
    <div className="min-h-screen bg-gray-100">
      <Head>
        <title>Sri Lanka Lak Travel Destination</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white  ">
        <section className="">
          <nav className="z-20 w-full lg:absolute">
            <Navbar />
          </nav>
                <img
                  src="https://i.imgur.com/OCysyuI.jpg"
                  className="w-screen lg:h-screen h-[50vh] object-cover"
                  alt="Background"
                />
          <div className="relative flex items-center justify-center bg-cover bg-center">
            <div className="bg-white bg-opacity-75 p-5 rounded-lg  text-center"></div>
          </div>
          <div className="text-4xl lg:px-16 px-5 mb-5 text-center font-sans"></div>
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 w-full lg:w-[80vw] mx-auto p-5"></div>
          <div className=" h-10"></div>
        </section>
      </main>
    </div>
  );
}
