import Footer from "@/components/footer";
import Navbar from "@/components/navigationBar";
import { ContactDetails } from "@/components/quickcontact";
import Head from "next/head";
import Link from "next/link";
import { IoIosArrowForward, IoMdDoneAll } from "react-icons/io";
import { MdHome } from "react-icons/md";
import Driver from "./driver";

export default function Home() {
  return (
    <div className="min-h-screen bg-gray-100">
      <Head>
        <title>Monkey Bird Travels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white  ">
        <section className="">
          <nav className="z-20 w-screen lg:absolute">
            <Navbar />
          </nav>
          <div className="relative w-screen h-full">
            <div className="relative w-screen h-full">
              <div className="relative w-screen h-full">
                <img
                  src="https://i.imgur.com/QdhxF3S.jpg"
                  className="w-screen lg:h-screen h-[50vh] object-cover"
                  alt="Background"
                />
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                  <div className="text-white text-4xl font-bold drop-shadow-md mb-4">
                    Private Driver
                  </div>
                  <div className="flex items-center text-white text-2xl font-bold drop-shadow-md">
                    <Link href="/">
                      {" "}
                      <MdHome color="" size={30} className="mr-2" />{" "}
                    </Link>
                    <span>
                      {" "}
                      <Link href="/">Home</Link>
                    </span>

                    <IoIosArrowForward color="" size={30} className="mx-2" />
                    <span>Private Driver</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="relative flex items-center justify-center bg-cover bg-center">
            <div className="bg-white bg-opacity-75 p-5 rounded-lg  text-center">
              <div className="text-3xl md:text-4xl lg:px-16 px-5 mb-5">
                <div className="font-semibold text-blue-600">
                  Your Trusted Private Driver Service
                </div>
              </div>
              <div className=" px-5 lg:px-16 font-medium flex-1 lg:flex">
                <img
                  src="https://i.imgur.com/c2DVMJA.png"
                  className="object-cover basis-1/4 w-full lg:w-1/4 shadow-xl rounded-lg m-4 h-full"
                  alt="Background"
                />

                <div className=" basis-1/2 text-slate-800 px-4 text-justify">
                  {" "}
                  Traveling in Sri Lanka has never been easier! With Monkeybird
                  Travels, you can hire a private car with an experienced and
                  knowledgeable driver to make your journey stress-free and
                  enjoyable. Whether you need a car for a day, a week, or even
                  longer, we offer flexible options tailored to your travel
                  plans. Choose from our wide range of vehicles, suitable for
                  any budget and group size. Our drivers are not just
                  chauffeurs—they are your local guides, ready to help you plan
                  your trip and recommend the must-see destinations across Sri
                  Lanka. From historic landmarks to scenic beaches and hidden
                  gems, we ensure you will have an unforgettable experience. If
                  you are looking for a convenient, safe, and personalized way
                  to explore Sri Lanka, Monkeybird Travels is here to take care
                  of all your travel needs. Contact us today and embark on a
                  journey of discovery, comfort, and adventure!
                  <div className="basis-1/2 text-slate-800 p-4">
                    <ul className=" columns-1 lg:columns-2 list-disc list-inside">
                      <li className=" flex">
                        {" "}
                        <IoMdDoneAll color="red" size={25} className="mr-2" />
                        Safe
                      </li>
                      <li className=" flex">
                        {" "}
                        <IoMdDoneAll color="red" size={25} className="mr-2" />
                        Available all the time
                      </li>
                      <li className=" flex">
                        {" "}
                        <IoMdDoneAll color="red" size={25} className="mr-2" />
                        Cheap in cost
                      </li>
                      <li className=" flex">
                        {" "}
                        <IoMdDoneAll color="red" size={25} className="mr-2" />
                        Easy to book
                      </li>
                      <li className=" flex">
                        {" "}
                        <IoMdDoneAll color="red" size={25} className="mr-2" />
                        Revise the Itinerary anytime
                      </li>
                      <li className=" flex">
                        {" "}
                        <IoMdDoneAll color="red" size={25} className="mr-2" />
                        Friendly
                      </li>
                    </ul>
                  </div>
                </div>

                <ContactDetails />
              </div>
            </div>
          </div>
          {/* <div className="text-4xl lg:px-16 px-5 mb-5 text-center font-sans">
            <div className="font-semibold text-blue-600">
              OUR PROFESSIONAL TEAM
            </div>
          </div> */}
          {/* <div className="grid grid-cols-1 lg:grid-cols-4 gap-3 w-full lg:w-[80vw] mx-auto p-5">
            <Driver
              name={"John Doe"}
              imgUrl={"https://i.imgur.com/OM4jnq8.jpg"}
              description={"PRIVATE DRIVER / GUIDE"}
            />
            <Driver
              name={"John Doe"}
              imgUrl={"https://i.imgur.com/OM4jnq8.jpg"}
              description={"PRIVATE DRIVER / GUIDE"}
            />
            <Driver
              name={"John Doe"}
              imgUrl={"https://i.imgur.com/OM4jnq8.jpg"}
              description={"PRIVATE DRIVER / GUIDE"}
            />
            <Driver
              name={"John Doe"}
              imgUrl={"https://i.imgur.com/OM4jnq8.jpg"}
              description={"PRIVATE DRIVER / GUIDE"}
            />
          </div> */}
        </section>
        <footer>
          <Footer />
        </footer>
      </main>
    </div>
  );
}
